[2025-02-21T14:47:35.240+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T14:47:35.261+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T14:47:33.913064+00:00 [queued]>
[2025-02-21T14:47:35.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T14:47:33.913064+00:00 [queued]>
[2025-02-21T14:47:35.270+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-21T14:47:35.283+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): run_spark_script> on 2025-02-21 14:47:33.913064+00:00
[2025-02-21T14:47:35.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T14:47:35.289+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-21T14:47:33.913064+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmpkjspfi1a']
[2025-02-21T14:47:35.290+0000] {standard_task_runner.py:72} INFO - Started process 96 to run task
[2025-02-21T14:47:35.290+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_spark_script
[2025-02-21T14:47:35.339+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T14:47:33.913064+00:00 [running]> on host 807a91bedaaf
[2025-02-21T14:47:35.423+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T14:47:33.913064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T14:47:33.913064+00:00'
[2025-02-21T14:47:35.424+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T14:47:35.461+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-21T14:47:35.463+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --driver-memory 4g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/scripts/ing_mov_20_21.py
[2025-02-21T14:47:36.883+0000] {spark_submit.py:641} INFO - Using properties file: null
[2025-02-21T14:47:36.985+0000] {spark_submit.py:641} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-02-21T14:47:36.986+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-02-21T14:47:36.987+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-02-21T14:47:36.987+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-02-21T14:47:36.987+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-02-21T14:47:36.988+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-02-21T14:47:36.988+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-02-21T14:47:36.988+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-02-21T14:47:36.989+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-02-21T14:47:36.989+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-02-21T14:47:36.989+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-02-21T14:47:37.016+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --driver-memory 4g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/scripts/ing_mov_20_21.py. Error code is: 1.
[2025-02-21T14:47:37.024+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-21T14:47:33.913064+00:00, execution_date=20250221T144733, start_date=20250221T144735, end_date=20250221T144737
[2025-02-21T14:47:37.056+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T14:47:37.057+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_spark_script (Cannot execute: spark-submit --master yarn --driver-memory 4g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/scripts/ing_mov_20_21.py. Error code is: 1.; 96)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --driver-memory 4g --name arrow-spark --verbose --queue root.default /opt/bitnami/spark/scripts/ing_mov_20_21.py. Error code is: 1.
[2025-02-21T14:47:37.074+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T14:47:37.098+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T14:47:37.100+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
