[2025-02-13T20:20:16.519+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T20:20:16.556+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T20:20:14.307501+00:00 [queued]>
[2025-02-13T20:20:16.584+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T20:20:14.307501+00:00 [queued]>
[2025-02-13T20:20:16.586+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T20:20:16.621+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-13 20:20:14.307501+00:00
[2025-02-13T20:20:16.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-13T20:20:14.307501+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmpgwfuvyyo']
[2025-02-13T20:20:16.632+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T20:20:16.635+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask run_spark_script
[2025-02-13T20:20:16.636+0000] {standard_task_runner.py:72} INFO - Started process 159 to run task
[2025-02-13T20:20:16.744+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T20:20:14.307501+00:00 [running]> on host 4dbe8526a981
[2025-02-13T20:20:16.979+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T20:20:14.307501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T20:20:14.307501+00:00'
[2025-02-13T20:20:16.981+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T20:20:17.011+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T20:20:17.013+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --packages org.apache.hadoop:hadoop-aws:3.3.6,com.amazonaws:aws-java-sdk-bundle:1.12.720 /opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-13T20:20:17.026+0000] {subprocess.py:99} INFO - Output:
[2025-02-13T20:20:20.504+0000] {subprocess.py:106} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-13T20:20:20.672+0000] {subprocess.py:106} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-02-13T20:20:20.676+0000] {subprocess.py:106} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-02-13T20:20:20.686+0000] {subprocess.py:106} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-02-13T20:20:20.687+0000] {subprocess.py:106} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-02-13T20:20:20.689+0000] {subprocess.py:106} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-085e0992-3d3e-42d1-9fdd-9f6c0ee5c75a;1.0
[2025-02-13T20:20:20.691+0000] {subprocess.py:106} INFO - 	confs: [default]
[2025-02-13T20:20:21.090+0000] {subprocess.py:106} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.6 in central
[2025-02-13T20:20:21.185+0000] {subprocess.py:106} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.1.3.Final in central
[2025-02-13T20:20:21.222+0000] {subprocess.py:106} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.720 in central
[2025-02-13T20:20:24.133+0000] {subprocess.py:106} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.720/aws-java-sdk-bundle-1.12.720.jar ...
[2025-02-13T20:22:32.507+0000] {job.py:229} INFO - Heartbeat recovered after 16.61 seconds
[2025-02-13T20:22:52.916+0000] {job.py:229} INFO - Heartbeat recovered after 30.72 seconds
[2025-02-13T20:23:14.049+0000] {job.py:229} INFO - Heartbeat recovered after 36.48 seconds
[2025-02-13T20:23:22.743+0000] {job.py:229} INFO - Heartbeat recovered after 24.77 seconds
[2025-02-13T20:23:38.919+0000] {job.py:229} INFO - Heartbeat recovered after 19.81 seconds
[2025-02-13T20:24:32.736+0000] {job.py:229} INFO - Heartbeat recovered after 64.94 seconds
[2025-02-13T20:25:25.649+0000] {job.py:229} INFO - Heartbeat recovered after 101.68 seconds
[2025-02-13T20:25:30.979+0000] {job.py:229} INFO - Heartbeat recovered after 53.19 seconds
[2025-02-13T20:26:10.463+0000] {job.py:229} INFO - Heartbeat recovered after 39.78 seconds
[2025-02-13T20:27:06.423+0000] {job.py:229} INFO - Heartbeat recovered after 90.41 seconds
[2025-02-13T20:27:11.485+0000] {job.py:229} INFO - Heartbeat recovered after 55.96 seconds
[2025-02-13T20:27:44.844+0000] {job.py:229} INFO - Heartbeat recovered after 13.10 seconds
[2025-02-13T20:27:49.904+0000] {job.py:229} INFO - Heartbeat recovered after 13.09 seconds
[2025-02-13T20:36:40.687+0000] {subprocess.py:106} INFO - :: resolution report :: resolve 559ms :: artifacts dl 979440ms
[2025-02-13T20:36:40.688+0000] {subprocess.py:106} INFO - 	:: modules in use:
[2025-02-13T20:36:40.689+0000] {subprocess.py:106} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.720 from central in [default]
[2025-02-13T20:36:40.693+0000] {subprocess.py:106} INFO - 	org.apache.hadoop#hadoop-aws;3.3.6 from central in [default]
[2025-02-13T20:36:40.695+0000] {subprocess.py:106} INFO - 	org.wildfly.openssl#wildfly-openssl;1.1.3.Final from central in [default]
[2025-02-13T20:36:40.698+0000] {subprocess.py:106} INFO - 	:: evicted modules:
[2025-02-13T20:36:40.698+0000] {subprocess.py:106} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.367 by [com.amazonaws#aws-java-sdk-bundle;1.12.720] in [default]
[2025-02-13T20:36:40.699+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-13T20:36:40.700+0000] {subprocess.py:106} INFO - 	|                  |            modules            ||   artifacts   |
[2025-02-13T20:36:40.701+0000] {subprocess.py:106} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-02-13T20:36:40.702+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-13T20:36:40.703+0000] {subprocess.py:106} INFO - 	|      default     |   4   |   0   |   0   |   1   ||   3   |   0   |
[2025-02-13T20:36:40.704+0000] {subprocess.py:106} INFO - 	---------------------------------------------------------------------
[2025-02-13T20:36:40.705+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.706+0000] {subprocess.py:106} INFO - :: problems summary ::
[2025-02-13T20:36:40.707+0000] {subprocess.py:106} INFO - :::: WARNINGS
[2025-02-13T20:36:40.708+0000] {subprocess.py:106} INFO - 		[FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.720!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (380383554) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.720/aws-java-sdk-bundle-1.12.720.jar. Please retry. (979396ms)
[2025-02-13T20:36:40.710+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.711+0000] {subprocess.py:106} INFO - 		[FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.12.720!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (380383554) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.720/aws-java-sdk-bundle-1.12.720.jar. Please retry. (979396ms)
[2025-02-13T20:36:40.712+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.713+0000] {subprocess.py:106} INFO - 	==== central: tried
[2025-02-13T20:36:40.714+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.715+0000] {subprocess.py:106} INFO - 	  https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.720/aws-java-sdk-bundle-1.12.720.jar
[2025-02-13T20:36:40.716+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.717+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-13T20:36:40.718+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.719+0000] {subprocess.py:106} INFO - 		::              FAILED DOWNLOADS            ::
[2025-02-13T20:36:40.726+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.727+0000] {subprocess.py:106} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-02-13T20:36:40.729+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.734+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-13T20:36:40.738+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.739+0000] {subprocess.py:106} INFO - 		:: com.amazonaws#aws-java-sdk-bundle;1.12.720!aws-java-sdk-bundle.jar
[2025-02-13T20:36:40.740+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.741+0000] {subprocess.py:106} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-02-13T20:36:40.741+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.742+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.745+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:36:40.746+0000] {subprocess.py:106} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-02-13T20:36:40.747+0000] {subprocess.py:106} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: com.amazonaws#aws-java-sdk-bundle;1.12.720!aws-java-sdk-bundle.jar]
[2025-02-13T20:36:40.747+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1613)
[2025-02-13T20:36:40.752+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-02-13T20:36:40.760+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:339)
[2025-02-13T20:36:40.774+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:969)
[2025-02-13T20:36:40.779+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
[2025-02-13T20:36:40.787+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
[2025-02-13T20:36:40.788+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-02-13T20:36:40.791+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-02-13T20:36:40.792+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-02-13T20:36:40.794+0000] {subprocess.py:106} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-02-13T20:36:40.795+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-13T20:36:40.828+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T20:36:40.860+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-13T20:20:14.307501+00:00, execution_date=20250213T202014, start_date=20250213T202016, end_date=20250213T203640
[2025-02-13T20:36:41.076+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:36:41.087+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 1.; 159)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T20:36:41.133+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T20:36:41.193+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T20:36:41.204+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
