[2025-02-21T12:36:28.719+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T12:36:28.739+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:36:27.721280+00:00 [queued]>
[2025-02-21T12:36:28.746+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:36:27.721280+00:00 [queued]>
[2025-02-21T12:36:28.747+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-21T12:36:28.759+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-21 12:36:27.721280+00:00
[2025-02-21T12:36:28.764+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=697) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T12:36:28.765+0000] {standard_task_runner.py:72} INFO - Started process 698 to run task
[2025-02-21T12:36:28.765+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-21T12:36:27.721280+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmpdt3c03t1']
[2025-02-21T12:36:28.766+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_spark_script
[2025-02-21T12:36:28.820+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:36:27.721280+00:00 [running]> on host b2dbcea502fb
[2025-02-21T12:36:28.900+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T12:36:27.721280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T12:36:27.721280+00:00'
[2025-02-21T12:36:28.901+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T12:36:28.913+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-21T12:36:28.914+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-21T12:36:28.921+0000] {subprocess.py:99} INFO - Output:
[2025-02-21T12:36:28.958+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-21T12:36:31.826+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO SparkContext: Running Spark version 3.5.0
[2025-02-21T12:36:31.828+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-02-21T12:36:31.829+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO SparkContext: Java version 17.0.14
[2025-02-21T12:36:31.875+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T12:36:31.943+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceUtils: ==============================================================
[2025-02-21T12:36:31.944+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-21T12:36:31.945+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceUtils: ==============================================================
[2025-02-21T12:36:31.945+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO SparkContext: Submitted application: Movies_20_21
[2025-02-21T12:36:31.962+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 8192, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-21T12:36:31.970+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-02-21T12:36:31.973+0000] {subprocess.py:106} INFO - 25/02/21 12:36:31 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-21T12:36:32.016+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SecurityManager: Changing view acls to: ***
[2025-02-21T12:36:32.016+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SecurityManager: Changing modify acls to: ***
[2025-02-21T12:36:32.017+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SecurityManager: Changing view acls groups to:
[2025-02-21T12:36:32.017+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SecurityManager: Changing modify acls groups to:
[2025-02-21T12:36:32.018+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-02-21T12:36:32.201+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO Utils: Successfully started service 'sparkDriver' on port 44991.
[2025-02-21T12:36:32.223+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SparkEnv: Registering MapOutputTracker
[2025-02-21T12:36:32.249+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-21T12:36:32.262+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-21T12:36:32.263+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-21T12:36:32.266+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-21T12:36:32.281+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f446c647-50c3-4356-9b6c-6d538f98e716
[2025-02-21T12:36:32.293+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-21T12:36:32.313+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-21T12:36:32.433+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-02-21T12:36:32.487+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-21T12:36:32.593+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-02-21T12:36:32.628+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.7:7077 after 20 ms (0 ms spent in bootstraps)
[2025-02-21T12:36:32.711+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250221123632-0001
[2025-02-21T12:36:32.714+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250221123632-0001/0 on worker-20250221115929-172.18.0.4-45097 (172.18.0.4:45097) with 1 core(s)
[2025-02-21T12:36:32.717+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneSchedulerBackend: Granted executor ID app-20250221123632-0001/0 on hostPort 172.18.0.4:45097 with 1 core(s), 8.0 GiB RAM
[2025-02-21T12:36:32.717+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250221123632-0001/1 on worker-20250221115929-172.18.0.3-39785 (172.18.0.3:39785) with 1 core(s)
[2025-02-21T12:36:32.720+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneSchedulerBackend: Granted executor ID app-20250221123632-0001/1 on hostPort 172.18.0.3:39785 with 1 core(s), 8.0 GiB RAM
[2025-02-21T12:36:32.733+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44077.
[2025-02-21T12:36:32.734+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO NettyBlockTransferService: Server created on b2dbcea502fb:44077
[2025-02-21T12:36:32.737+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-21T12:36:32.738+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250221123632-0001/1 is now RUNNING
[2025-02-21T12:36:32.741+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b2dbcea502fb, 44077, None)
[2025-02-21T12:36:32.745+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManagerMasterEndpoint: Registering block manager b2dbcea502fb:44077 with 434.4 MiB RAM, BlockManagerId(driver, b2dbcea502fb, 44077, None)
[2025-02-21T12:36:32.746+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b2dbcea502fb, 44077, None)
[2025-02-21T12:36:32.747+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b2dbcea502fb, 44077, None)
[2025-02-21T12:36:32.821+0000] {subprocess.py:106} INFO - 25/02/21 12:36:32 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250221123632-0001/0 is now RUNNING
[2025-02-21T12:36:33.022+0000] {subprocess.py:106} INFO - 25/02/21 12:36:33 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-02-21T12:36:35.822+0000] {subprocess.py:106} INFO - 25/02/21 12:36:35 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:49248) with ID 1,  ResourceProfileId 0
[2025-02-21T12:36:35.925+0000] {subprocess.py:106} INFO - 25/02/21 12:36:35 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:44989 with 4.6 GiB RAM, BlockManagerId(1, 172.18.0.3, 44989, None)
[2025-02-21T12:36:35.945+0000] {subprocess.py:106} INFO - 25/02/21 12:36:35 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.4:50734) with ID 0,  ResourceProfileId 0
[2025-02-21T12:36:36.006+0000] {subprocess.py:106} INFO - 25/02/21 12:36:36 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.4:42913 with 4.6 GiB RAM, BlockManagerId(0, 172.18.0.4, 42913, None)
[2025-02-21T13:08:06.916+0000] {subprocess.py:106} INFO - 25/02/21 13:08:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-02-21T13:08:06.925+0000] {subprocess.py:106} INFO - 25/02/21 13:08:06 INFO SharedState: Warehouse path is 'file:/tmp/***tmpwk487scy/spark-warehouse'.
[2025-02-21T13:08:08.358+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-21T13:08:08.359+0000] {subprocess.py:106} INFO -   File "/opt/bitnami/spark/scripts/ing_mov_20_21.py", line 131, in <module>
[2025-02-21T13:08:08.363+0000] {subprocess.py:106} INFO -     .save("s3a://bronze/movie_20_21/")
[2025-02-21T13:08:08.364+0000] {subprocess.py:106} INFO -      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-21T13:08:08.364+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1463, in save
[2025-02-21T13:08:08.364+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-02-21T13:08:08.365+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-02-21T13:08:08.365+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-02-21T13:08:08.366+0000] {subprocess.py:106} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o57.save.
[2025-02-21T13:08:08.366+0000] {subprocess.py:106} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T13:08:08.366+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-02-21T13:08:08.367+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-02-21T13:08:08.367+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-02-21T13:08:08.369+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-02-21T13:08:08.370+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-02-21T13:08:08.371+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-02-21T13:08:08.372+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-02-21T13:08:08.372+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-02-21T13:08:08.372+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:454)
[2025-02-21T13:08:08.373+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:530)
[2025-02-21T13:08:08.373+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
[2025-02-21T13:08:08.373+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
[2025-02-21T13:08:08.374+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
[2025-02-21T13:08:08.376+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-21T13:08:08.376+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-02-21T13:08:08.377+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-21T13:08:08.377+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-02-21T13:08:08.377+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-02-21T13:08:08.378+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-21T13:08:08.380+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-02-21T13:08:08.387+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-02-21T13:08:08.388+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-02-21T13:08:08.389+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-21T13:08:08.390+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-21T13:08:08.391+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-21T13:08:08.391+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T13:08:08.392+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-02-21T13:08:08.392+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-02-21T13:08:08.393+0000] {subprocess.py:106} INFO - 	... 24 more
[2025-02-21T13:08:08.393+0000] {subprocess.py:106} INFO - 
[2025-02-21T13:08:08.531+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-21T13:08:08.532+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-02-21T13:08:08.542+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkUI: Stopped Spark web UI at http://b2dbcea502fb:4040
[2025-02-21T13:08:08.547+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-21T13:08:08.547+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-02-21T13:08:08.579+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-21T13:08:08.603+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO MemoryStore: MemoryStore cleared
[2025-02-21T13:08:08.603+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO BlockManager: BlockManager stopped
[2025-02-21T13:08:08.608+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-21T13:08:08.610+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-21T13:08:08.626+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: Successfully stopped SparkContext
[2025-02-21T13:08:08.626+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T13:08:08.627+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-d41b3e75-8c1a-4f1f-8adf-8f9aefeb8a5c/pyspark-fe4cac73-b2ab-4b3a-9938-87d7fc800798
[2025-02-21T13:08:08.629+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-d41b3e75-8c1a-4f1f-8adf-8f9aefeb8a5c
[2025-02-21T13:08:08.633+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-9fce5edb-c0ec-481c-b513-0b10e6c3c3bd
[2025-02-21T13:08:08.660+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-21T13:08:08.672+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T13:08:08.678+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-21T12:36:27.721280+00:00, execution_date=20250221T123627, start_date=20250221T123628, end_date=20250221T130808
[2025-02-21T13:08:08.710+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T13:08:08.710+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 1.; 698)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T13:08:08.719+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T13:08:08.739+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T13:08:08.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
