[2025-02-21T12:00:43.520+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T12:00:43.539+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [queued]>
[2025-02-21T12:00:43.547+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [queued]>
[2025-02-21T12:00:43.547+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-21T12:00:43.559+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-21 12:00:42.315427+00:00
[2025-02-21T12:00:43.563+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T12:00:43.565+0000] {standard_task_runner.py:72} INFO - Started process 74 to run task
[2025-02-21T12:00:43.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-21T12:00:42.315427+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmppxnn4bdv']
[2025-02-21T12:00:43.566+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_spark_script
[2025-02-21T12:00:43.614+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [running]> on host b2dbcea502fb
[2025-02-21T12:00:43.690+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T12:00:42.315427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T12:00:42.315427+00:00'
[2025-02-21T12:00:43.691+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T12:00:43.720+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-21T12:00:43.721+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-21T12:00:43.728+0000] {subprocess.py:99} INFO - Output:
[2025-02-21T12:00:43.772+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-21T12:00:47.381+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SparkContext: Running Spark version 3.5.0
[2025-02-21T12:00:47.388+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-02-21T12:00:47.388+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SparkContext: Java version 17.0.14
[2025-02-21T12:00:47.530+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T12:00:47.660+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceUtils: ==============================================================
[2025-02-21T12:00:47.661+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-21T12:00:47.661+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceUtils: ==============================================================
[2025-02-21T12:00:47.662+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SparkContext: Submitted application: Movies_20_21
[2025-02-21T12:00:47.689+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 8192, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-21T12:00:47.702+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-02-21T12:00:47.703+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-21T12:00:47.793+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SecurityManager: Changing view acls to: ***
[2025-02-21T12:00:47.793+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SecurityManager: Changing modify acls to: ***
[2025-02-21T12:00:47.794+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SecurityManager: Changing view acls groups to:
[2025-02-21T12:00:47.794+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SecurityManager: Changing modify acls groups to:
[2025-02-21T12:00:47.795+0000] {subprocess.py:106} INFO - 25/02/21 12:00:47 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-02-21T12:00:48.004+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO Utils: Successfully started service 'sparkDriver' on port 35983.
[2025-02-21T12:00:48.036+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO SparkEnv: Registering MapOutputTracker
[2025-02-21T12:00:48.070+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-21T12:00:48.085+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-21T12:00:48.085+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-21T12:00:48.090+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-21T12:00:48.113+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f5896054-0690-40db-8171-9c49bbf85775
[2025-02-21T12:00:48.127+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-21T12:00:48.141+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-21T12:00:48.309+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-02-21T12:00:48.384+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-21T12:00:48.510+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-02-21T12:00:48.550+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.7:7077 after 21 ms (0 ms spent in bootstraps)
[2025-02-21T12:00:48.665+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250221120048-0000
[2025-02-21T12:00:48.673+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37117.
[2025-02-21T12:00:48.674+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO NettyBlockTransferService: Server created on b2dbcea502fb:37117
[2025-02-21T12:00:48.675+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-21T12:00:48.703+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250221120048-0000/0 on worker-20250221115929-172.18.0.4-45097 (172.18.0.4:45097) with 1 core(s)
[2025-02-21T12:00:48.707+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneSchedulerBackend: Granted executor ID app-20250221120048-0000/0 on hostPort 172.18.0.4:45097 with 1 core(s), 8.0 GiB RAM
[2025-02-21T12:00:48.708+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250221120048-0000/1 on worker-20250221115929-172.18.0.3-39785 (172.18.0.3:39785) with 1 core(s)
[2025-02-21T12:00:48.709+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneSchedulerBackend: Granted executor ID app-20250221120048-0000/1 on hostPort 172.18.0.3:39785 with 1 core(s), 8.0 GiB RAM
[2025-02-21T12:00:48.709+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b2dbcea502fb, 37117, None)
[2025-02-21T12:00:48.710+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManagerMasterEndpoint: Registering block manager b2dbcea502fb:37117 with 434.4 MiB RAM, BlockManagerId(driver, b2dbcea502fb, 37117, None)
[2025-02-21T12:00:48.716+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b2dbcea502fb, 37117, None)
[2025-02-21T12:00:48.717+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b2dbcea502fb, 37117, None)
[2025-02-21T12:00:48.897+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250221120048-0000/1 is now RUNNING
[2025-02-21T12:00:48.901+0000] {subprocess.py:106} INFO - 25/02/21 12:00:48 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250221120048-0000/0 is now RUNNING
[2025-02-21T12:00:49.064+0000] {subprocess.py:106} INFO - 25/02/21 12:00:49 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-02-21T12:00:51.655+0000] {subprocess.py:106} INFO - 25/02/21 12:00:51 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.3:47740) with ID 1,  ResourceProfileId 0
[2025-02-21T12:00:51.679+0000] {subprocess.py:106} INFO - 25/02/21 12:00:51 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.4:54788) with ID 0,  ResourceProfileId 0
[2025-02-21T12:00:51.771+0000] {subprocess.py:106} INFO - 25/02/21 12:00:51 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.4:42529 with 4.6 GiB RAM, BlockManagerId(0, 172.18.0.4, 42529, None)
[2025-02-21T12:00:51.780+0000] {subprocess.py:106} INFO - 25/02/21 12:00:51 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.3:39709 with 4.6 GiB RAM, BlockManagerId(1, 172.18.0.3, 39709, None)
[2025-02-21T12:33:10.293+0000] {subprocess.py:106} INFO - 25/02/21 12:33:10 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-02-21T12:33:10.301+0000] {subprocess.py:106} INFO - 25/02/21 12:33:10 INFO SharedState: Warehouse path is 'file:/tmp/***tmp59_9lgir/spark-warehouse'.
[2025-02-21T12:33:11.653+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-21T12:33:11.654+0000] {subprocess.py:106} INFO -   File "/opt/bitnami/spark/scripts/ing_mov_20_21.py", line 131, in <module>
[2025-02-21T12:33:11.655+0000] {subprocess.py:106} INFO -     .save("s3a://bronze/movie_20_21/")
[2025-02-21T12:33:11.656+0000] {subprocess.py:106} INFO -      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-21T12:33:11.656+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1463, in save
[2025-02-21T12:33:11.656+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-02-21T12:33:11.657+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-02-21T12:33:11.657+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-02-21T12:33:11.657+0000] {subprocess.py:106} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o57.save.
[2025-02-21T12:33:11.658+0000] {subprocess.py:106} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T12:33:11.658+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-02-21T12:33:11.659+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-02-21T12:33:11.659+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-02-21T12:33:11.659+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-02-21T12:33:11.660+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-02-21T12:33:11.660+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-02-21T12:33:11.660+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-02-21T12:33:11.661+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-02-21T12:33:11.661+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:454)
[2025-02-21T12:33:11.662+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:530)
[2025-02-21T12:33:11.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
[2025-02-21T12:33:11.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
[2025-02-21T12:33:11.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
[2025-02-21T12:33:11.664+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-21T12:33:11.664+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-02-21T12:33:11.664+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-21T12:33:11.664+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-02-21T12:33:11.665+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-02-21T12:33:11.665+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-21T12:33:11.665+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-02-21T12:33:11.665+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-02-21T12:33:11.666+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-02-21T12:33:11.666+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-21T12:33:11.666+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-21T12:33:11.667+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-21T12:33:11.667+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T12:33:11.667+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-02-21T12:33:11.667+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-02-21T12:33:11.668+0000] {subprocess.py:106} INFO - 	... 24 more
[2025-02-21T12:33:11.668+0000] {subprocess.py:106} INFO - 
[2025-02-21T12:33:11.820+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-21T12:33:11.821+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-02-21T12:33:11.833+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO SparkUI: Stopped Spark web UI at http://b2dbcea502fb:4040
[2025-02-21T12:33:11.842+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-21T12:33:11.848+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-02-21T12:33:11.896+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-21T12:33:11.958+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO MemoryStore: MemoryStore cleared
[2025-02-21T12:33:11.959+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO BlockManager: BlockManager stopped
[2025-02-21T12:33:11.963+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-21T12:33:11.965+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-21T12:33:11.978+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO SparkContext: Successfully stopped SparkContext
[2025-02-21T12:33:11.978+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T12:33:11.979+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-c1df885f-43db-42e1-9f83-cb75c9820fc6
[2025-02-21T12:33:11.982+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-c1df885f-43db-42e1-9f83-cb75c9820fc6/pyspark-1e9ac58b-37ed-4b8a-9d18-a928531723dc
[2025-02-21T12:33:11.985+0000] {subprocess.py:106} INFO - 25/02/21 12:33:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-3aa1af04-17b8-42ad-aeb5-11c19380689c
[2025-02-21T12:33:12.027+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-21T12:33:12.040+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T12:33:12.047+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-21T12:00:42.315427+00:00, execution_date=20250221T120042, start_date=20250221T120043, end_date=20250221T123312
[2025-02-21T12:33:12.084+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T12:33:12.084+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 1.; 74)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T12:33:12.095+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T12:33:12.116+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T12:33:12.117+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
